// Code generated by "stringer -type=AromaType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CITRUS-0]
	_ = x[FRUITY-1]
	_ = x[FLORAL-2]
	_ = x[HERBAL-3]
	_ = x[GREEN-4]
	_ = x[SPICY-5]
	_ = x[SULFUROUS-6]
	_ = x[EARTHY-7]
	_ = x[WOODY-8]
	_ = x[NUTTY-9]
	_ = x[SMOKY-10]
	_ = x[CREAMY-11]
	_ = x[FERMENTED-12]
	_ = x[OTHER-13]
}

const _AromaType_name = "CITRUSFRUITYFLORALHERBALGREENSPICYSULFUROUSEARTHYWOODYNUTTYSMOKYCREAMYFERMENTEDOTHER"

var _AromaType_index = [...]uint8{0, 6, 12, 18, 24, 29, 34, 43, 49, 54, 59, 64, 70, 79, 84}

func (i AromaType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AromaType_index)-1 {
		return "AromaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AromaType_name[_AromaType_index[idx]:_AromaType_index[idx+1]]
}
