// Code generated by "stringer -type=TasteType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SWEET-0]
	_ = x[SOUR-1]
	_ = x[SALTY-2]
	_ = x[BITTER-3]
	_ = x[UMAMI-4]
}

const _TasteType_name = "SWEETSOURSALTYBITTERUMAMI"

var _TasteType_index = [...]uint8{0, 5, 9, 14, 20, 25}

func (i TasteType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TasteType_index)-1 {
		return "TasteType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TasteType_name[_TasteType_index[idx]:_TasteType_index[idx+1]]
}
