// Code generated by "stringer -type=IngredientType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VEGETABLE-0]
	_ = x[FRUIT-1]
	_ = x[HERB-2]
	_ = x[SPICE-3]
	_ = x[GRAIN-4]
	_ = x[LEGUME-5]
	_ = x[NUT-6]
	_ = x[SEED-7]
	_ = x[DAIRY-8]
	_ = x[MEAT-9]
	_ = x[FISH-10]
	_ = x[FUNGUS-11]
	_ = x[OTHER-12]
}

const _IngredientType_name = "VEGETABLEFRUITHERBSPICEGRAINLEGUMENUTSEEDDAIRYMEATFISHFUNGUSOTHER"

var _IngredientType_index = [...]uint8{0, 9, 14, 18, 23, 28, 34, 37, 41, 46, 50, 54, 60, 65}

func (i IngredientType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IngredientType_index)-1 {
		return "IngredientType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IngredientType_name[_IngredientType_index[idx]:_IngredientType_index[idx+1]]
}
